#!/bin/bash
# 🆘 ONE-LINE HELP COMMAND
# The absolute simplest way to get help

echo ""
echo "══════════════════════════════════════════════════════════"
echo "🆘 AI MUSIC SUITE - QUICK HELP"
echo "══════════════════════════════════════════════════════════"
echo ""
echo "🚀 FASTEST WAY TO START:"
echo "   python3 start.py              # Interactive menu"
echo ""
echo "🎵 LAUNCH INDIVIDUAL TOOLS:"
echo "   python3 logic_copilot_lite.py    # Music AI Chat"
echo "   python3 ai_mixing_engineer.py    # Audio Analysis"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "   python3 help.py               # Check what's wrong"
echo "   ./fix-everything.sh           # Fix everything"
echo ""
echo "📚 READ GUIDES:"
echo "   cat YOUR-ONLY-HOPE.md         # Quick help"
echo "   cat TROUBLESHOOTING.md        # Detailed solutions"
echo "   cat START-HERE.md             # Complete setup"
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
echo "💡 Most common fixes:"
echo ""
echo "   # Missing dependencies?"
echo "   pip3 install gradio together python-dotenv"
echo ""
echo "   # No API keys?"
echo "   cp config_example.txt .env"
echo "   nano .env  # Add your keys"
echo ""
echo "   # Port in use?"
echo "   kill -9 \$(lsof -t -i:7860)"
echo ""
echo "══════════════════════════════════════════════════════════"
echo ""
