services:
  - type: web
    name: docs-agent-api
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: INDEX_DIR
        value: /app/index
      - key: DOCS_API_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

