#!/usr/bin/env bash
# 🎨 Vibe Coding Environment - Master Installation Script
# One-command setup for the ultimate macOS dev environment

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                                 ║"
echo "║          🎨 Vibe Coding Environment Installer 🎨               ║"
echo "║                                                                 ║"
echo "║     Ultimate macOS setup for multi-AI, multi-tool creators     ║"
echo "║                                                                 ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "This will set up:"
echo "  • Homebrew + dev tools (Node, Python, Docker, etc.)"
echo "  • IDE configurations (Cursor, VS Code Insiders, Windsurf)"
echo "  • Enhanced shell (.zshrc with AI integrations)"
echo "  • Bitwarden CLI for secure API key management"
echo "  • Tokyo Night theme + JetBrains Mono font"
echo "  • Global shortcuts via Hammerspoon"
echo "  • Lo-fi music integration"
echo "  • AI tools (OpenRouter, Kimi K2, Hugging Face, Copilot)"
echo "  • Terminal dashboard with system monitoring"
echo ""
read -p "🚀 Ready to begin? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Installation cancelled."
    exit 1
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 1/9: Core Tools Installation"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/00-main-setup.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 2/9: IDE Detection & Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/01-detect-ides.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 3/9: Shell Environment Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/02-zshrc-config.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 4/9: Bitwarden Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/03-bitwarden-setup.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 5/9: Theme & Aesthetics"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/04-theme-setup.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 6/9: Global Shortcuts"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/05-global-shortcuts.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 7/9: Music Integration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/06-music-integration.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 8/9: AI Tool Integrations"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/07-ai-integrations.sh"

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Phase 9/9: Terminal Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bash "$SCRIPT_DIR/08-terminal-dashboard.sh"

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                                 ║"
echo "║              ✅ Installation Complete! ✅                       ║"
echo "║                                                                 ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "🎉 Vibe Coding Environment is ready!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Next Steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  Restart your terminal or run:"
echo "    source ~/.zshrc"
echo ""
echo "2️⃣  Login to Bitwarden and load API keys:"
echo "    bw login"
echo "    bwload"
echo ""
echo "3️⃣  Add your API keys to Bitwarden vault:"
echo "    • OpenRouter API"
echo "    • Hugging Face Token"
echo "    • OpenAI API Key"
echo "    • Anthropic API Key"
echo ""
echo "4️⃣  Test the setup:"
echo "    vibe_start      # Start vibe session"
echo "    vibe-dash       # Show dashboard"
echo "    vibe-help       # Show all commands"
echo "    ai-ask 'Hello!' # Test AI integration"
echo ""
echo "5️⃣  Optional manual steps:"
echo "    • Import Tokyo Night theme in Terminal/iTerm2"
echo "    • Grant Hammerspoon Accessibility permissions"
echo "    • Login to GitHub CLI: gh auth login"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⌨️  Global Shortcuts:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⌘ ⌥ G  → GitHub Copilot | ⌘ ⌥ A  → Terminal"
echo "⌘ ⌥ C  → Cursor         | ⌘ ⌥ M  → Music"
echo "⌘ ⌥ D  → Dashboard      | ⌘ ⌥ S  → AI Status"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 Happy Vibe Coding! 🚀"
echo ""

