name: Security Scan

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit
      
      - name: Check for vulnerable dependencies
        run: |
          pip install -r requirements.txt || true
          safety check --json > safety_report.json || true
          cat safety_report.json
      
      - name: Run bandit security scan
        run: |
          bandit -r . -f json -o bandit_report.json || true
          cat bandit_report.json
      
      - name: Scan for exposed secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
      
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            safety_report.json
            bandit_report.json
          retention-days: 90
      
      - name: Check for API keys in code
        run: |
          echo "Scanning for potential API keys in code..."
          if grep -r "sk-[a-zA-Z0-9]\{32,\}" --exclude-dir=.git --exclude="*.md" .; then
            echo "::error::Potential API keys found in code!"
            exit 1
          fi
          if grep -r "AKIA[0-9A-Z]\{16\}" --exclude-dir=.git --exclude="*.md" .; then
            echo "::error::Potential AWS keys found in code!"
            exit 1
          fi
          echo "✅ No exposed keys found"
      
      - name: Create security issue on findings
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔒 Security Scan Alert: Vulnerabilities Detected',
              body: `## Security Scan Results
              
              Security vulnerabilities or issues were detected during automated scanning.
              
              **Scan Date:** ${new Date().toISOString()}
              **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
              
              Please review the security reports in the workflow artifacts and take appropriate action.
              
              ### Next Steps:
              1. Review the security scan results
              2. Update vulnerable dependencies
              3. Remove any exposed secrets
              4. Apply security patches
              `,
              labels: ['security', 'automated', 'priority-critical']
            });
